apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-cluster
  namespace: default
spec:
  image: phuhv102/bigdata:flink-xgboost
  flinkVersion: v1_18
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    
    metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    metrics.reporter.prom.port: 9249
  serviceAccount: flink

  jobManager:
    resource:
      memory: "1024m"
      cpu: 1
    podTemplate:
      spec:
        containers:
          - name: flink-main-container
            imagePullPolicy: Always
            volumeMounts:
              - name: models-volume
                mountPath: /mnt/models
        volumes:
          - name: models-volume
            hostPath:
              path: /mnt/models
              type: DirectoryOrCreate

  taskManager:
    resource:
      memory: "1024m"
      cpu: 1
    podTemplate:
      spec:
        containers:
          - name: flink-main-container
            imagePullPolicy: Always
            volumeMounts:
              - name: models-volume
                mountPath: /mnt/models
        volumes:
          - name: models-volume
            hostPath:
              path: /mnt/models
              type: DirectoryOrCreate

  job:
    jarURI: local:///mnt/models/realtime-fraud-detection-1.0-SNAPSHOT.jar
    entryClass: org.example.FraudDetectionJob
    args:
      - --bootstrap.servers
      - kafka:29092
      - --redis.host
      - redis
      - --redis.port
      - "6379"
      - --minio.endpoint
      - http://minio:9000
      - --minio.bucket
      - fraud-data-lake
      - --minio.accessKey
      - minioadmin
      - --minio.secretKey
      - minioadmin

    parallelism: 1
    upgradeMode: stateless