apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - name: external
      port: 9092
      targetPort: 9092

    - name: internal
      port: 29092
      targetPort: 29092

    - name: controller
      port: 9093
      targetPort: 9093

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka

spec:
  serviceName: kafka
  replicas: 3

  selector:
    matchLabels:
      app: kafka

  template:
    metadata:
      labels:
        app: kafka

    spec:
      enableServiceLinks: false

      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.6.0

          ports:
            - containerPort: 9092
            - containerPort: 29092
            - containerPort: 9093

          env:
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"

            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"

            - name: KAFKA_LISTENERS
              value: "INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"

            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-0.kafka:9093,2@kafka-1.kafka:9093,3@kafka-2.kafka:9093"

            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"

            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"

            - name: CLUSTER_ID
              value: "MkU3OEVBNTcwNTJENDM2Qk"

            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"

            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "3"

            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "2"

            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "false"

          command:
            - sh
            - -c
            - |
              export KAFKA_NODE_ID=$((${HOSTNAME##*-}+1))

              export KAFKA_ADVERTISED_LISTENERS=INTERNAL://${HOSTNAME}.kafka:29092,EXTERNAL://${HOSTNAME}.kafka:9092

              exec /etc/confluent/docker/run