kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  # Port dành cho Kafka External Access
  - containerPort: 30092
    hostPort: 30092
    protocol: TCP
  # Port dành cho MinIO Console
  - containerPort: 30090
    hostPort: 30090
    protocol: TCP
  # Port dành cho Grafana Dashboard
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP