# minio-values.yaml - Official MinIO (đã tối ưu cho Kind)

mode: standalone
replicas: 1

rootUser: "admin"
rootPassword: "YourStrongPassword123!"

image:
  repository: quay.io/minio/minio
  tag: "latest"
  pullPolicy: IfNotPresent

console:
  enabled: true
  image:
    repository: quay.io/minio/console
    tag: "latest"
    pullPolicy: IfNotPresent

persistence:
  enabled: true
  size: 50Gi
  storageClass: ""          # local-path trên Kind

service:
  type: ClusterIP
  port: 9000
  consolePort: 9001

# Tắt provisioning job để tránh timeout (bạn tạo bucket sau cũng được)
provisioning:
  enabled: false

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 2Gi
    cpu: 1000m

metrics:
  enabled: false

ingress:
  enabled: false