apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      containers:
        - name: taskmanager
          image: flink:1.18.1-java11
          args: ["taskmanager"]
          volumeMounts:
            - name: models-volume
              mountPath: /mnt/models
          env:
            - name: FLINK_PROPERTIES
              value: |
                jobmanager.rpc.address: jobmanager
                taskmanager.numberOfTaskSlots: 2
      volumes:
        - name: models-volume
          hostPath:
            path: /mnt/models
            type: DirectoryOrCreate